services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_NUM_CTX=32768
      - OLLAMA_NUM_GPU=12
      - OLLAMA_GPU_MEMORY_FRACTION=0.8
      - OLLAMA_CPU_THREADS=12
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11434"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10m  # Increased for multiple model downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 20G
        reservations:
          memory: 12G

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ollama-api
    ports:
      - "3001:3001"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_URL=http://ollama:11434
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: ./ollama-vision-chat
      dockerfile: Dockerfile
    container_name: ollama-frontend
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local